config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/about'
  
  get 'search', to:"units#search"
  
  resources :units do
    member do
      get :download
    end
  end
  
  resources :units do
    member do
      get :download_excel
      get :download_excel_file2
    end
  end

  resources :units do
    member do
      get :combined_pdf
      get :combined_pdf2
    end
  end 

  get '/compare_units', to: 'units#compare_units', as: 'compare_units'
  get '/compare_units/download_excel', to: 'units#download_comparison_excel', as: 'download_comparison_excel'
  get '/compare_units/download_pdf', to: 'units#download_comparison_pdf', as: 'download_comparison_pdf'


  match '/generate_file', to: 'tests#generate_file', via: [:get, :post]

  resources :tests, only: [:index, :create] do
    collection do
      get 'run_test_page'
      get 'new_test'
      post 'check_radios'
      post 'test_mode'
      get 'run_ble_test'
      post 'run_ble_test_action'
    end
  end

end

app/models/unit.rb
class Unit < ApplicationRecord
    has_one_attached :text_file
    has_one_attached :second_text_file
end

app/controllers/units_controller.rb
require 'axlsx'
include ApplicationHelper
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end
  
  def search
    @units = Unit.where("serial_number LIKE ? OR description LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
  end

  def compare_units
    # Retrieve selected unit IDs from params
    selected_unit_ids = params[:selected_units]

    # Fetch the corresponding units
    @selected_units = Unit.where(id: selected_unit_ids)

    # Initialize a hash to store the data
    @combined_data = Hash.new { |hash, key| hash[key] = {} }

    @selected_units.each do |unit|
      if unit.text_file.attached?
        text_file_content = unit.text_file.download
        # Call your function to extract data for each unit
        data_for_unit = extract_data_from_text_file(text_file_content)
        
      else
        data_for_unit = []
      end

      #Delete end of list repeats
      data_for_unit = data_for_unit[0...-4]
      #Rails.logger.debug "Data for unit #{unit.id}: #{data_for_unit.inspect}"

      # Populate the combined_data hash
      data_for_unit.each do |data|
        key = "#{data[:test]}|#{data[:name]}|#{data[:range]}"
        #Rails.logger.debug "Storing value #{data[:value]} for key #{key} and unit #{unit.id}"
        @combined_data[key][unit.id] = data[:value]
      end

    end
    @combined_data 
    #Rails.logger.debug "Combined data: #{@combined_data.inspect}"
  end

  def download_comparison_excel
    # Use the same logic to retrieve selected units and combined data
    selected_unit_ids = params[:selected_units]
    @selected_units = Unit.where(id: selected_unit_ids)
    @combined_data = Hash.new { |hash, key| hash[key] = {} }
  
    @selected_units.each do |unit|
      if unit.text_file.attached?
        text_file_content = unit.text_file.download
        data_for_unit = extract_data_from_text_file(text_file_content)
      else
        data_for_unit = []
      end
  
      # Remove end-of-list repeats
      data_for_unit = data_for_unit[0...-4]
  
      # Populate combined_data
      data_for_unit.each do |data|
        key = "#{data[:test]}|#{data[:name]}|#{data[:range]}"
        @combined_data[key][unit.id] = data[:value]
      end
    end
  
    # Generate the Excel file
    xlsx_package = Axlsx::Package.new
    wb = xlsx_package.workbook
  
    # Add a worksheet
    wb.add_worksheet(name: "Comparison Results") do |sheet|
      # Add headers
      headers = ["Test", "Name", "Range"]
      @selected_units.each do |unit|
        headers << unit.serial_number
      end
      header_style = sheet.styles.add_style(b: true, border: { style: :thin, color: '000000' })
      sheet.add_row headers, style: [header_style] * headers.size
  
      # Add data rows
      @combined_data.each do |key, values|
        test, name, range = key.split('|', 3)
        row = [test, name, range]
        row_styles = [nil, nil, nil]

        @selected_units.each do |unit|
          value = values[unit.id] || ""
          row << value
          value_class = calculate_value_class(value, range, name)
          row_styles << sheet.styles.add_style(bg_color: value_class_to_color(value_class), border: { style: :thin, color: '000000' })
        end

        sheet.add_row row, style: row_styles
      end
    end
  
    # Send the file to the user
    send_data xlsx_package.to_stream.read,
              filename: "comparison_results.xlsx",
              type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  def download_comparison_pdf
    # Retrieve selected unit IDs from params
    selected_unit_ids = params[:selected_units]
  
    # Fetch the corresponding units
    @selected_units = Unit.where(id: selected_unit_ids)
  
    # Initialize a hash to store the data
    @combined_data = Hash.new { |hash, key| hash[key] = {} }
  
    @selected_units.each do |unit|
      if unit.text_file.attached?
        text_file_content = unit.text_file.download
        # Call your function to extract data for each unit
        data_for_unit = extract_data_from_text_file(text_file_content)
      else
        data_for_unit = []
      end
  
      # Remove end-of-list repeats
      data_for_unit = data_for_unit[0...-4]
  
      # Populate the combined_data hash
      data_for_unit.each do |data|
        key = "#{data[:test]}|#{data[:name]}|#{data[:range]}"
        @combined_data[key][unit.id] = data[:value]
      end
    end
  
    # Create a PDF document
    pdf = Prawn::Document.new
    image_path = Rails.root.join('app', 'assets', 'images', 'ALTICE_LABS_LOGO_POS_HOR_TRANS_RGB.png').to_s
    add_watermark(pdf, image_path)
  
    pdf.text "Comparison of Units", size: 18, style: :bold, align: :center
    pdf.move_down 20
  
    # Add table headers
    table_data = [["Test", "Name", "Range"] + @selected_units.map(&:serial_number)]
  
    # Add table rows
    @combined_data.each do |key, values|
      test, name, range = key.split('|', 3)
      row = [test, name, range]
      @selected_units.each do |unit|
        value = values[unit.id] || "N/A"
        value_class = calculate_value_class(value, range, name)
        value_color = value_class_to_color(value_class)
        row << { content: value.to_s, background_color: value_color }
      end
      table_data << row
    end
  
    # Add table to PDF
    pdf.table(table_data, header: true, cell_style: { borders: [:top, :bottom, :left, :right], padding: 5, border_width: 0.5 }) do
      cells.style(align: :center)
      row(0).style(background_color: 'AAAAAA', text_color: 'FFFFFF', size: 12, font_style: :bold)
    end
  
    # Send the PDF to the browser
    send_data pdf.render, filename: "comparison_results.pdf", type: "application/pdf", disposition: "inline"
  end 

  def value_class_to_color(value_class)
    case value_class
    when 'table-success'
      '90EE90' # Light Green
    when 'table-danger'
      'FF6347' # Tomato Red
    else
      'FFFFFF' # Default White
    end
  end

  def download
    @unit = Unit.find(params[:id])
  
    if @unit.text_file.attached?
      send_data @unit.text_file.download, filename: "#{@unit.serial_number}.txt"
    else
      flash[:error] = 'Text file not found.'
      redirect_to unit_path(@unit)
    end
  end

  def download_excel
    @unit = Unit.find(params[:id])
  
    if @unit.text_file.attached?
      text_file_content = @unit.text_file.download
      @extracted_data = extract_data_from_text_file(text_file_content)
  
      xlsx_package = Axlsx::Package.new
      wb = xlsx_package.workbook
  
      # Add a worksheet
      wb.add_worksheet(name: "Unit Data") do |sheet|
        # Add data to the worksheet
        header_style = sheet.styles.add_style(b: true, border: { style: :thin, color: '000000' })
        # Add the header row with bold and borders
        sheet.add_row ["Test", "Name", "Range", "Value"], style: [header_style] * 4
        @extracted_data.each do |values|
          test_description = values[:test]
          test_type = test_description.include?("TX_VERIFY") ? "TX" : "RX"
  
          case test_type
          when "TX"
            add_tx_data(sheet, values)
          when "RX"
            add_rx_data(sheet, values)
          end
          # Apply styles based on value class
          value_class = calculate_value_class(values[:value], values[:range], values[:name])
          value_style = sheet.styles.add_style(bg_color: value_class_to_color(value_class), border: { style: :thin, color: '000000' })
          sheet.rows.last.cells[3].style = value_style
        end
      end
  
      send_data xlsx_package.to_stream.read, filename: "#{@unit.serial_number}.xlsx"
    else
      flash[:error] = 'Text file not found.'
      redirect_to unit_path(@unit)
    end
  end

  def download_excel_file2
    @unit = Unit.find(params[:id])
  
    if @unit.second_text_file.attached?
      text_file_content = @unit.second_text_file.download
      @extracted_data = extract_data_from_2text_file(text_file_content)
  
      xlsx_package = Axlsx::Package.new
      wb = xlsx_package.workbook
  
      # Add a worksheet
      wb.add_worksheet(name: "Unit Data") do |sheet|
        # Add data to the worksheet
        header_style = sheet.styles.add_style(b: true, border: { style: :thin, color: '000000' })
        # Add the header row with bold and borders
        sheet.add_row ["Test", "Name", "Range", "Value"], style: [header_style] * 4
        @extracted_data.each do |values|
          test_description = values[:test]
          test_type = test_description.include?("TX_") ? "TX" : "RX"
  
          case test_type
            #add_iot_tx_data
          when "TX"
            add_tx_iot_data(sheet, values)
          when "RX"
            add_rx_iot_data(sheet, values)
          end
          # Apply styles based on value class
          value_class = calculate_value_class(values[:value], values[:range], values[:name])
          value_style = sheet.styles.add_style(bg_color: value_class_to_color(value_class), border: { style: :thin, color: '000000' })
          sheet.rows.last.cells[3].style = value_style
        end
      end
  
      send_data xlsx_package.to_stream.read, filename: "#{@unit.serial_number}.xlsx"
    else
      flash[:error] = 'Text file not found.'
      redirect_to unit_path(@unit)
    end
  end
  
  def combined_pdf
    @unit = Unit.find(params[:id])
  
    # Fetch first data (e.g., serial number, description, or info from text file)
    first_data = fetch_first_data(@unit)
  
    # Fetch second data (e.g., extract specific data from the text file)
    second_data = extract_data_from_text_file(@unit.text_file.download)  # Assuming you have text_file attached to the unit
  
    # Generate the PDF
    pdf = Prawn::Document.new
     # Add watermark image to all pages

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit, local: true, multipart: true, class: "form-container") do |form| %>
  <% if @unit.errors.any? %>
    <div class="alert alert-danger" id="error_explanation">
      <h4 class="alert-heading"><%= pluralize(@unit.errors.count, "error") %> prevented this unit from being saved:</h4>
      <ul>
        <% @unit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :serial_number, class: "form-label" %>
    <%= form.number_field :serial_number, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.select :description, ['D222AH', 'XSR250GK', 'XSR240LNR', 'XSR140LNR'], {}, class: "form-select" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :text_file, "Wi-Fi Text File", class: "form-label" %>
    <%= form.file_field :text_file, class: "form-control" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :second_text_file, "BLE+ZigBee Text File", class: "form-label" %>
    <%= form.file_field :second_text_file, class: "form-control" %>
  </div>

  <div class="form-group mt-4">
    <%= form.submit "Create Unit", class: "btn btn-primary w-100" %>
  </div>
<% end %>

#TODO when creating new unit and alread used serial number is entered it should add file if missing or give some error message

app/views/units/_unit.html.erb
<div id="<%= dom_id unit %>">
  <p>
    <strong>Serial number:</strong>
    <%= unit.serial_number %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= unit.description %>
  </p>


</div>

app/views/units/compare_units.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test Results</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      margin: 0;
      padding: 0;
      background-color: #f9f9f9;
      color: #333;
    }

    h1 {
      text-align: center;
      margin: 20px 0;
      color: #0056b3;
    }

        .table-success {
      background-color: #d4edda; /* Light green */
      color: #155724; /* Dark green text */
    }

    .table-danger {
      background-color: #f8d7da; /* Light red */
      color: #721c24; /* Dark red text */
    }

    .table-default {
      background-color: #ffffff; /* White */
      color: #333333; /* Default text color */
    }

    table {
      width: 90%;
      max-width: 1000px;
      margin: 20px auto;
      border-collapse: collapse;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
      background-color: #fff;
    }

    th, td {
      border: 1px solid #ddd;
      padding: 10px;
      text-align: left;
    }

    th {
      background-color: #0056b3;
      color: #fff;
      font-weight: bold;
    }

    tr:nth-child(even) {
      background-color: #f2f2f2;
    }

    tr:hover {
      background-color: #e6f7ff;
    }

    td {
      text-align: center;
    }

    @media screen and (max-width: 768px) {
      table {
        width: 100%;
        font-size: 14px;
      }

      th, td {
        padding: 8px;
      }
    }
  </style>
  <h1>Test Results</h1>
  <body>
    <div class="button-container">
    <%= link_to 'Download Excel', download_comparison_excel_path(selected_units: @selected_units.map(&:id)), 
                class: 'btn btn-primary' %>
    <%= link_to 'Download PDF', download_comparison_pdf_path(selected_units: @selected_units.map(&:id)), 
                class: 'btn btn-danger' %>
  </div>
  <table>
    <thead>
      <tr>
        <th>Test</th>
        <th>Name</th>
        <th>Range</th>
        <% @selected_units.each do |unit| %>
          <th><%= unit.serial_number %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @combined_data.each do |key, values| %>
        <% test, name, range = key.split('|', 3) %>
        <tr>
          <td><%= test %></td>
          <td><%= name %></td>
          <td><%= range %></td>
          <% @selected_units.each do |unit| %>
            <td class="<%= calculate_value_class(values[unit.id], range, name) %>">
              <%= "#{values[unit.id]}" || "" %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

</html>

#TODO COMPARE BLE+ZigBee files add an option

app/views/units/edit.html.erb
<h1>Editing unit</h1>

<%= render "form", unit: @unit %>

<br>


<div>
  <%= link_to "Show this unit", @unit %> |
  <%= link_to "Back to units", units_path %>
</div>

app/views/units/index.html.erb
<p class="text-success"><%= notice %></p>

<div class="container">
  <h1 class="my-4">Units</h1>

  <table class="table table-hover table-bordered" style="background-color: #ffffff; border-color: #c0c0c0;">
    <thead style="background-color: #e0e0e0;"> <!-- Medium gray header -->
      <tr>
        <th scope="col">SN</th>
        <th scope="col">Description</th>
        <th scope="col">Function</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @units.each do |unit| %>
        <tr>
          <td><%= unit.serial_number %></td>
          <td><%= unit.description %></td>
          <td><%= link_to "Show this unit", unit, class: "btn btn-info btn-sm" %></td>
          <td><%= button_to "Destroy", unit, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="my-3">
    <%= link_to "New unit", new_unit_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/units/new.html.erb
<div class="container my-5">
  <h1 class="display-4 text-center mb-4">New Unit</h1>

  <div class="card p-4 shadow-sm">
    <%= render "form", unit: @unit %>
  </div>

  <div class="text-center mt-4">
    <%= link_to "Back to Units", units_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/units/search.erb
<h1 class="page-title">Search Results</h1>

<%= form_tag(compare_units_path, method: :get, id: 'compareForm', class: 'form-container') do %>
  <div class="units-grid">
    <% @units.each do |unit| %>
      <div class="unit-card">
        <div class="unit-details">
          <%= render unit %>
        </div>
        <div class="unit-actions">
          <%= link_to "Show this unit", unit_path(unit), class: 'btn btn-primary btn-sm' %>
          <div class="checkbox-container">
            <%= check_box_tag 'selected_units[]', unit.id, false, class: 'unit-checkbox' %>
            <%= label_tag "selected_units_#{unit.id}", 'Select for comparison', class: 'checkbox-label' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="form-actions">
    <%= submit_tag 'Compare Selected Units', id: 'compareSelected', class: 'btn btn-success btn-lg' %>
  </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('compareSelected').addEventListener('click', function() {
      document.getElementById('compareForm').submit();
    });
  });
</script>

app/views/units/show.html.erb
<p class="text-success"><%= notice %></p>

<div class="container">
  <!-- Unit Header Section -->
  <h2 class="text-center my-4">Unit LOGs</h2>
  <h3 class="text-muted text-center"><%= @unit.serial_number %></h3>

  <!-- Unit Description Section -->
  <div class="mb-4 text-center">
    <p><strong>Description:</strong> <%= @unit.description %></p>
  </div>

<%# <!-- File Upload Form Section --> %>
<%# <%= form_for @unit, html: { multipart: true, class: 'text-center' } do |f| %>
<%#   <div class="form-group mb-3"> %>
<%#     <%= f.file_field :text_file, class: "form-control-file" %>
<%#   </div> %>
<%#   <%= f.submit "Import", class: "btn btn-primary btn-lg mb-4" %>
<%# <% end %>


  <!-- Download Links Section -->
  <% if @unit.text_file.attached? %>
    <h2 class="text-center my-4">Wi-Fi Test Results</h2>
    <div class="d-flex justify-content-center mb-4">
      <div class="btn-group">
        <%= link_to 'Download Text File', download_unit_path(@unit), class: 'btn btn-secondary btn-lg' %>
        <%= link_to 'Download Excel File', download_excel_unit_path(@unit), class: 'btn btn-success btn-lg' %>
        <%= link_to 'Download PDF', combined_pdf_unit_path(@unit), class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  <% end %>

  <% if @unit.second_text_file.attached? %>
    <h2 class="text-center my-4">BLE+ZigBee Test Results</h2>
    <div class="d-flex justify-content-center mb-4">
      <div class="btn-group">
        <%= link_to 'Download Text File', rails_blob_path(@unit.second_text_file), class: 'btn btn-secondary btn-lg' %>
        <%= link_to 'Download Excel File', download_excel_file2_unit_path(@unit), class: 'btn btn-success btn-lg' %>
        <%= link_to 'Download PDF', combined_pdf2_unit_path(@unit), class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
  <% end %>

<div class="row">
  <!-- First Table -->
  <% if @extracted_data.present? %>
    <div class="col-6">
      <h3 class="text-center">Wi-Fi</h3>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Test</th>
              <th scope="col">Name</th>
              <th scope="col">Range</th>
              <th scope="col">Value</th>
            </tr>
          </thead>
          <tbody>
            <% grouped_data = @extracted_data[0...-4].group_by { |data| data[:test] } %>
            <% colors = ['table-primary', 'table-secondary'] %>
            <% grouped_data.each_with_index do |(test, rows), index| %>
              <% row_class = colors[index % 2] %>
              <% rows.each do |data| %>
                <tr class="<%= row_class %>">
                  <td><%= data[:test] %></td>
                  <td><%= data[:name] %></td>
                  <td><%= data[:range] %></td>
                  <td class="<%= calculate_value_class(data[:value], data[:range], data[:name]) %>">
                    <%= data[:value] %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>

  <!-- Second Table -->
  <% if @extracted_data_second_file.present? %>
    <div class="col-6">
      <h3 class="text-center">BLE+ZigBee</h3>
      <div class="table-responsive">
        <table class="table table-bordered table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col">Test</th>
              <th scope="col">Name</th>
              <th scope="col">Range</th>
              <th scope="col">Value</th>
            </tr>
          </thead>
          <tbody>
            <% grouped_data = @extracted_data_second_file.group_by { |data| data[:test] } %>
            <% grouped_data.each_with_index do |(test, rows), index| %>
              <% row_class = colors[index % 2] %>
              <% rows.each do |data| %>
                <tr class="<%= row_class %>">
                  <td><%= data[:test] %></td>
                  <td><%= data[:name] %></td>
                  <td><%= data[:range] %></td>
                  <td class="<%= calculate_value_class(data[:value], data[:range], data[:name]) %>">
                    <%= data[:value] %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>

  <!-- Action Buttons Section -->
<div class="text-center mt-4">
    <%= link_to "Edit this unit", edit_unit_path(@unit), class:"btn btn-secondary mr-2" %>
    <%= link_to "Back to units", units_path, class:"btn btn-secondary" %>
    <%= button_to "Destroy this unit", @unit, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger ml-2" %>
  </div>
</div>